version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
